spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hfl_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
logging:
  level:
    pers.hfl.hflblog.dao: trace
setting:
  path: D:/myCode/hfl-blog/blog-back-end/back-end-api/src/main/resources/hflblog.setting
